[server]
address = "127.0.0.1:8000"

[observability]
level = "debug"
endpoint = "http://0.0.0.0:4317"

[static_file]
path = "output"

[turnstile]
route = "https://challenges.cloudflare.com/turnstile/v0/siteverify"
secret = "1x0000000000000000000000000000000AA"
