[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }